/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova;





/**
 *
 * @author Ivan
 */
public class LjubavniKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form LjubavniKalkulator
     */
    public LjubavniKalkulator() {
        initComponents();
    }

static int[] stvaranjeMatrice(String ime1, String ime2) {

			String manji = ime1.length() < ime2.length() ? ime1.toLowerCase() : ime2.toLowerCase();
			String veci = ime1.length() < ime2.length() ? ime2.toLowerCase() : ime1.toLowerCase();

			String ime = manji + veci;

			int[] imena = new int[ime.length()];

			for (int i = 0; i < ime.length(); i++) {
				for (int j = 0; j < ime.length(); j++) {
					if (ime.charAt(i) == ime.charAt(j)) {
						imena[i] += 1;
					}
				}
			}
			
			imena = razdvajanjeDvoznamenkastih(imena);

			int[] matrica = new int[veci.length()];

			for (int i = 0; i < matrica.length; i++) {
				if (manji.toCharArray().length > i) {
					matrica[i] += imena[i];
				}

				if (veci.toCharArray().length > i) {
					matrica[i] += imena[imena.length - 1 - i];
				}
			}
			return razdvajanjeDvoznamenkastih(matrica);
		}

		static int[] analiza(int[] niz) {

			if (niz.length <= 2) {
				return niz;
			} else {
				if (niz.length % 2 == 0) {
					int[] zbroj = new int[niz.length / 2];

					for (int i = 0; i < niz.length; i++) {

						if (i < niz.length - 1 - i) {
							zbroj[i] = niz[i] + niz[niz.length - 1 - i];
						}

					}

					return analiza(razdvajanjeDvoznamenkastih(zbroj));

				} else {
					int[] zbroj = new int[(niz.length / 2) + 1];

					for (int i = 0; i < niz.length; i++) {

						if (i < niz.length - 1 - i) {

							zbroj[i] = niz[i] + niz[niz.length - 1 - i];
						}

						if (niz[i] == niz[niz.length - 1 - i]) {
							zbroj[i] = niz[i];
							break;
						}

					}

					return analiza(razdvajanjeDvoznamenkastih(zbroj));

				}

			}

		}

		static int[] razdvajanjeDvoznamenkastih(int[] niz) {

			int brojac = 0;
			for (int i : niz) {
				if (i >= 10) {
					brojac++;
				}
			}

			int[] pomocnaMatrica = new int[niz.length + brojac];

			for (int i = 0, j = 0; i < niz.length; i++) {
				if (niz[i] < 10) {
					pomocnaMatrica[j++] = niz[i];
				} else {
					pomocnaMatrica[j++] = niz[i] / 10;
					pomocnaMatrica[j++] = niz[i] % 10;
				}
			}

			return pomocnaMatrica;
		}

	
	
	
	
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrvoime = new javax.swing.JTextField();
        btnStart = new java.awt.Button();
        lblIme = new javax.swing.JLabel();
        lblDrugoIme = new javax.swing.JTextField();
        lblImesimpatije = new javax.swing.JLabel();
        lblizracun = new javax.swing.JLabel();
        pb = new javax.swing.JProgressBar();
        lblRezultat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblPrvoime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrvoime.setForeground(new java.awt.Color(153, 51, 0));
        lblPrvoime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPrvoimeActionPerformed(evt);
            }
        });

        btnStart.setLabel("Pokreni kalkulator");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblIme.setBackground(java.awt.SystemColor.activeCaptionBorder);
        lblIme.setText("Unesi svoje ime:");

        lblDrugoIme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDrugoIme.setForeground(new java.awt.Color(153, 51, 0));
        lblDrugoIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDrugoImeActionPerformed(evt);
            }
        });

        lblImesimpatije.setBackground(java.awt.SystemColor.activeCaptionBorder);
        lblImesimpatije.setText("Unesi ime simpatije:");

        lblizracun.setText("Saznaj koliko se volite ");

        lblRezultat.setText("Rezultat");
        lblRezultat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblizracun)
                            .addComponent(lblDrugoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImesimpatije)
                            .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrvoime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrvoime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImesimpatije, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDrugoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblizracun)
                .addGap(22, 22, 22)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrvoimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPrvoimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPrvoimeActionPerformed

    private void lblDrugoImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDrugoImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDrugoImeActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
                String ime1 = lblPrvoime.getText();
		String ime2 = lblDrugoIme.getText();
		String konacno = "";
                for (int i : analiza(stvaranjeMatrice(ime1, ime2))) {
			konacno += i;
		}
                
                if(ime1.isEmpty() || ime2.isEmpty()){
                    lblRezultat.setText("Potrebno je upisati imena u predviđena polja!");
                } else {
                    lblRezultat.setText(ime1 + " i " + ime2 + " vole se " + konacno + "% !");
                }   
    }//GEN-LAST:event_btnStartActionPerformed

    
    
     





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnStart;
    private javax.swing.JTextField lblDrugoIme;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblImesimpatije;
    private javax.swing.JTextField lblPrvoime;
    private javax.swing.JLabel lblRezultat;
    private javax.swing.JLabel lblizracun;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
}
